# https://github.com/fdhadzh/flask-pipenv-example
FROM python:3.7

RUN pip3 install poetry

WORKDIR /usr/src/app

COPY poetry.lock ./
COPY pyproject.toml ./

RUN set -ex && poetry install --no-dev

COPY . .
